// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResiCare.Infrastructure.Persistence;

#nullable disable

namespace ResiCare.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260619223112_AddCaregiverAuth")]
    partial class AddCaregiverAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResiCare.Domain.Entities.CareTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CompletedByCaregiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByCaregiverId");

                    b.HasIndex("ResidentId", "ScheduledDate");

                    b.ToTable("CareTasks", (string)null);
                });

            modelBuilder.Entity("ResiCare.Domain.Entities.Caregiver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Caregivers", (string)null);
                });

            modelBuilder.Entity("ResiCare.Domain.Entities.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaregiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CaregiverId");

                    b.HasIndex("ResidentId", "CreatedAt");

                    b.ToTable("Observations", (string)null);
                });

            modelBuilder.Entity("ResiCare.Domain.Entities.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AdmissionDate")
                        .HasColumnType("date");

                    b.Property<string>("AttendingPhysician")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("FallRisk")
                        .HasColumnType("int");

                    b.Property<string>("Family")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Interests")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MalnutritionRisk")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PressureSoreRisk")
                        .HasColumnType("int");

                    b.Property<Guid>("ReferentCaregiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ReferentCaregiverId");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Residents", (string)null);
                });

            modelBuilder.Entity("ResiCare.Domain.Entities.CareTask", b =>
                {
                    b.HasOne("ResiCare.Domain.Entities.Caregiver", null)
                        .WithMany()
                        .HasForeignKey("CompletedByCaregiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResiCare.Domain.Entities.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ResiCare.Domain.Entities.Observation", b =>
                {
                    b.HasOne("ResiCare.Domain.Entities.Caregiver", null)
                        .WithMany()
                        .HasForeignKey("CaregiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResiCare.Domain.Entities.Resident", null)
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ResiCare.Domain.Entities.Resident", b =>
                {
                    b.HasOne("ResiCare.Domain.Entities.Caregiver", null)
                        .WithMany()
                        .HasForeignKey("ReferentCaregiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ResiCare.Domain.ValueObjects.DependencyProfile", "Dependency", b1 =>
                        {
                            b1.Property<Guid>("ResidentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Dressing")
                                .HasColumnType("int");

                            b1.Property<int>("Eating")
                                .HasColumnType("int");

                            b1.Property<int>("Elimination")
                                .HasColumnType("int");

                            b1.Property<int>("Hygiene")
                                .HasColumnType("int");

                            b1.Property<int>("Mobility")
                                .HasColumnType("int");

                            b1.HasKey("ResidentId");

                            b1.ToTable("Residents");

                            b1.WithOwner()
                                .HasForeignKey("ResidentId");
                        });

                    b.Navigation("Dependency")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
